#compiler: ghc-8.0.2
resolver: lts-8.18
flags: {}
packages:
- transient
- transient-universe
# - axiom
# - ghcjs-perch
# - haskell-do
extra-deps:
- hashtables-1.2.1.1
- clay-0.12.1
- flow-1.0.7
- HTTP-4000.3.6
- RefSerialize-0.4.0
- SHA-1.6.4.2
- TCache-0.12.1
- appar-0.1.4
- attoparsec-0.13.1.0
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- byteorder-1.0.4
- case-insensitive-1.2.0.8
- entropy-0.3.7
- ghcjs-perch-0.3.3.2
- hashable-1.2.6.0
- hashtables-1.2.1.1
- integer-logarithms-1.0.1
- iproute-1.7.1
- mtl-2.2.1
- network-2.6.3.1
- network-info-0.2.0.8
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.4.11
- stm-2.4.4.1
- stringsearch-0.3.6.6
- text-1.2.2.1
- vector-0.12.0.1
- websockets-0.10.0.0

